version: '3'
services:
  mydb:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ozone
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ozonedb

  app:
    depends_on:
      - mydb
    image: back-dev-o-zone:latest

    ports:
      - 9000:9000
    environment:
      - POSTGRES_USER=ozone
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ozonedb
    restart: always

volumes:
  db_data: {}
